import { Question, STATUS } from './types';

export const DEFAULT_QUESTIONS_A: Question[] = [
  { letter: "A", answer: "Abuelo", description: "Padre del padre o de la madre.", condition: "Empieza por A" },
  { letter: "B", answer: "Biberón", description: "Botella con tetina para la lactancia artificial.", condition: "Empieza por B" },
  { letter: "C", answer: "Cicatriz", description: "Señal que queda en los tejidos después de curar una herida.", condition: "Empieza por C" },
  { letter: "D", answer: "Débil", description: "De poco vigor o de poca fuerza o resistencia.", condition: "Empieza por D" },
  { letter: "E", answer: "Echar", description: "Hacer que algo vaya a parar a alguna parte, dándole impulso.", condition: "Empieza por E" },
  { letter: "F", answer: "Fábula", description: "Breve relato ficticio, en prosa o verso, con intención didáctica.", condition: "Empieza por F" },
  { letter: "G", answer: "Gota", description: "Pequeña porción de líquido con forma esferoidal.", condition: "Empieza por G" },
  { letter: "H", answer: "Historia", description: "Narración y exposición de los acontecimientos pasados.", condition: "Empieza por H" },
  { letter: "I", answer: "Ilusión", description: "Esperanza cuyo cumplimiento parece especialmente atractivo.", condition: "Empieza por I" },
  { letter: "J", answer: "Jabalí", description: "Mamífero paquidermo de la familia del cerdo.", condition: "Empieza por J" },
  { letter: "K", answer: "Kilo", description: "Unidad de masa del Sistema Internacional.", condition: "Empieza por K" },
  { letter: "L", answer: "Ladrón", description: "Que hurta o roba.", condition: "Empieza por L" },
  { letter: "M", answer: "Mañana", description: "Tiempo futuro más o menos próximo.", condition: "Empieza por M" },
  { letter: "N", answer: "Nadar", description: "Dicho de una persona o de un animal: Trasladarse en el agua.", condition: "Empieza por N" },
  { letter: "Ñ", answer: "Ñu", description: "Mamífero rumiante africano de la familia de los antílopes.", condition: "Contiene la Ñ" },
  { letter: "O", answer: "Oasis", description: "Sitio con vegetación y a veces con manantiales en los desiertos.", condition: "Empieza por O" },
  { letter: "P", answer: "Paciencia", description: "Capacidad de padecer o soportar algo sin alterarse.", condition: "Empieza por P" },
  { letter: "Q", answer: "Químico", description: "Perteneciente o relativo a la química.", condition: "Empieza por Q" },
  { letter: "R", answer: "Ratón", description: "Mamífero roedor de pequeño tamaño.", condition: "Empieza por R" },
  { letter: "S", answer: "Sabio", description: "Dicho de una persona: Que posee sabiduría.", condition: "Empieza por S" },
  { letter: "T", answer: "Tabaco", description: "Planta de la familia de las solanáceas.", condition: "Empieza por T" },
  { letter: "U", answer: "Urgencia", description: "Cualidad de urgente.", condition: "Empieza por U" },
  { letter: "V", answer: "Vaca", description: "Hembra del toro.", condition: "Empieza por V" },
  { letter: "W", answer: "Web", description: "Red informática.", condition: "Contiene la W" },
  { letter: "X", answer: "Xilófono", description: "Instrumento musical de percusión.", condition: "Empieza por X" },
  { letter: "Y", answer: "Yegua", description: "Hembra del caballo.", condition: "Empieza por Y" },
  { letter: "Z", answer: "Zapato", description: "Calzado que no pasa del tobillo.", condition: "Empieza por Z" },
];

export const DEFAULT_QUESTIONS_B: Question[] = [
  { letter: "A", answer: "Amigo", description: "Que tiene amistad.", condition: "Empieza por A" },
  { letter: "B", answer: "Balón", description: "Pelota grande usada en diversos deportes.", condition: "Empieza por B" },
  { letter: "C", answer: "Caballo", description: "Mamífero solípedo, perisodáctilo, de la familia de los équidos.", condition: "Empieza por C" },
  { letter: "D", answer: "Dedo", description: "Cada uno de los cinco apéndices articulados de la mano.", condition: "Empieza por D" },
  { letter: "E", answer: "Elefante", description: "Mamífero proboscidio, el mayor de los terrestres.", condition: "Empieza por E" },
  { letter: "F", answer: "Fuego", description: "Fenómeno caracterizado por la emisión de calor y de luz.", condition: "Empieza por F" },
  { letter: "G", answer: "Gato", description: "Mamífero carnívoro de la familia de los félidos.", condition: "Empieza por G" },
  { letter: "H", answer: "Hielo", description: "Agua convertida en cuerpo sólido por descenso de la temperatura.", condition: "Empieza por H" },
  { letter: "I", answer: "Isla", description: "Porción de tierra rodeada de agua por todas partes.", condition: "Empieza por I" },
  { letter: "J", answer: "Juego", description: "Acción y efecto de jugar.", condition: "Empieza por J" },
  { letter: "K", answer: "Karate", description: "Modalidad de lucha japonesa.", condition: "Empieza por K" },
  { letter: "L", answer: "León", description: "Gran mamífero carnívoro de la familia de los félidos.", condition: "Empieza por L" },
  { letter: "M", answer: "Música", description: "Arte de combinar los sonidos de la voz humana o instrumentos.", condition: "Empieza por M" },
  { letter: "N", answer: "Nube", description: "Masa de vapor acuoso suspendida en la atmósfera.", condition: "Empieza por N" },
  { letter: "Ñ", answer: "Caña", description: "Tallo de las plantas gramíneas.", condition: "Contiene la Ñ" },
  { letter: "O", answer: "Ojo", description: "Órgano de la vista.", condition: "Empieza por O" },
  { letter: "P", answer: "Perro", description: "Mamífero doméstico de la familia de los cánidos.", condition: "Empieza por P" },
  { letter: "Q", answer: "Queso", description: "Producto obtenido por maduración de la cuajada de la leche.", condition: "Empieza por Q" },
  { letter: "R", answer: "Río", description: "Corriente de agua continua y más o menos caudalosa.", condition: "Empieza por R" },
  { letter: "S", answer: "Sol", description: "Estrella luminosa, centro de nuestro sistema planetario.", condition: "Empieza por S" },
  { letter: "T", answer: "Tren", description: "Medio de transporte que circula sobre raíles.", condition: "Empieza por T" },
  { letter: "U", answer: "Uva", description: "Baya o grano, fruto de la vid.", condition: "Empieza por U" },
  { letter: "V", answer: "Viento", description: "Corriente de aire producida en la atmósfera.", condition: "Empieza por V" },
  { letter: "W", answer: "Whisky", description: "Bebida alcohólica obtenida por destilación.", condition: "Contiene la W" },
  { letter: "X", answer: "Xenofobia", description: "Fobia a los extranjeros.", condition: "Empieza por X" },
  { letter: "Y", answer: "Yate", description: "Embarcación de gala o de recreo.", condition: "Empieza por Y" },
  { letter: "Z", answer: "Zorro", description: "Mamífero cánido de hocico puntiagudo y cola larga.", condition: "Empieza por Z" },
];

export const INITIAL_STATE = (questions: Question[]): Question[] =>
  questions.map(q => ({ ...q, status: STATUS.PENDING }));

