import { Question, STATUS } from './types';

export const DEFAULT_QUESTIONS_A: Question[] = [
  { letter: "A", answer: "Casa", description: "Edificio para habitar.", condition: "Contiene la A" },
  { letter: "B", answer: "Biberón", description: "Botella con tetina para la lactancia artificial.", condition: "Empieza por B" },
  { letter: "C", answer: "Cicatriz", description: "Señal que queda en los tejidos después de curar una herida.", condition: "Empieza por C" },
  { letter: "D", answer: "Codo", description: "Articulación del brazo con el antebrazo.", condition: "Contiene la D" },
  { letter: "E", answer: "Mesa", description: "Mueble compuesto de un tablero horizontal sostenido por uno o varios pies.", condition: "Contiene la E" },
  { letter: "F", answer: "Fábula", description: "Breve relato ficticio, en prosa o verso, con intención didáctica.", condition: "Empieza por F" },
  { letter: "G", answer: "Lago", description: "Masa de agua dulce o salada, de extensión considerable, separada del mar.", condition: "Contiene la G" },
  { letter: "H", answer: "Chico", description: "Muchacho, niño o joven.", condition: "Contiene la H" },
  { letter: "I", answer: "Ilusión", description: "Esperanza cuyo cumplimiento parece especialmente atractivo.", condition: "Empieza por I" },
  { letter: "J", answer: "Caja", description: "Recipiente, por lo común de forma prismática o cilíndrica, con tapa.", condition: "Contiene la J" },
  { letter: "K", answer: "Kilo", description: "Unidad de masa del Sistema Internacional.", condition: "Empieza por K" },
  { letter: "L", answer: "Ladrón", description: "Que hurta o roba.", condition: "Empieza por L" },
  { letter: "M", answer: "Cama", description: "Mueble destinado para dormir.", condition: "Contiene la M" },
  { letter: "N", answer: "Lana", description: "Pelo de las ovejas y de otros animales, que se hila y se teje.", condition: "Contiene la N" },
  { letter: "Ñ", answer: "Ñu", description: "Mamífero rumiante africano de la familia de los antílopes.", condition: "Empieza por Ñ" },
  { letter: "O", answer: "Oasis", description: "Sitio con vegetación y a veces con manantiales en los desiertos.", condition: "Empieza por O" },
  { letter: "P", answer: "Capa", description: "Prenda de vestir larga y suelta, sin mangas, abierta por delante.", condition: "Contiene la P" },
  { letter: "Q", answer: "Químico", description: "Perteneciente o relativo a la química.", condition: "Empieza por Q" },
  { letter: "R", answer: "Cara", description: "Parte anterior de la cabeza del ser humano.", condition: "Contiene la R" },
  { letter: "S", answer: "Sabio", description: "Dicho de una persona: Que posee sabiduría.", condition: "Empieza por S" },
  { letter: "T", answer: "Tabaco", description: "Planta de la familia de las solanáceas.", condition: "Empieza por T" },
  { letter: "U", answer: "Cuba", description: "Recipiente grande, más ancho que alto, de madera, metal u otro material.", condition: "Contiene la U" },
  { letter: "V", answer: "Vaca", description: "Hembra del toro.", condition: "Empieza por V" },
  { letter: "W", answer: "Web", description: "Red informática.", condition: "Empieza por W" },
  { letter: "X", answer: "Xilófono", description: "Instrumento musical de percusión.", condition: "Empieza por X" },
  { letter: "Y", answer: "Yegua", description: "Hembra del caballo.", condition: "Empieza por Y" },
  { letter: "Z", answer: "Lazo", description: "Cinta, cordón o cosa semejante que se ata formando uno o más nudos.", condition: "Contiene la Z" },
];

export const DEFAULT_QUESTIONS_B: Question[] = [
  { letter: "A", answer: "Amigo", description: "Que tiene amistad.", condition: "Empieza por A" },
  { letter: "B", answer: "Cabeza", description: "Parte superior del cuerpo del ser humano.", condition: "Contiene la B" },
  { letter: "C", answer: "Caballo", description: "Mamífero solípedo, perisodáctilo, de la familia de los équidos.", condition: "Empieza por C" },
  { letter: "D", answer: "Lado", description: "Cada una de las dos partes en que se considera dividida una cosa.", condition: "Contiene la D" },
  { letter: "E", answer: "Elefante", description: "Mamífero proboscidio, el mayor de los terrestres.", condition: "Empieza por E" },
  { letter: "F", answer: "Café", description: "Bebida que se hace por infusión con los granos tostados y molidos del cafeto.", condition: "Contiene la F" },
  { letter: "G", answer: "Gato", description: "Mamífero carnívoro de la familia de los félidos.", condition: "Empieza por G" },
  { letter: "H", answer: "Chico", description: "Muchacho, niño o joven.", condition: "Contiene la H" },
  { letter: "I", answer: "Cita", description: "Concertar una entrevista o encuentro.", condition: "Contiene la I" },
  { letter: "J", answer: "Juego", description: "Acción y efecto de jugar.", condition: "Empieza por J" },
  { letter: "K", answer: "Karate", description: "Modalidad de lucha japonesa.", condition: "Empieza por K" },
  { letter: "L", answer: "León", description: "Gran mamífero carnívoro de la familia de los félidos.", condition: "Empieza por L" },
  { letter: "M", answer: "Música", description: "Arte de combinar los sonidos de la voz humana o instrumentos.", condition: "Empieza por M" },
  { letter: "N", answer: "Lana", description: "Pelo de las ovejas y de otros animales, que se hila y se teje.", condition: "Contiene la N" },
  { letter: "Ñ", answer: "Caña", description: "Tallo de las plantas gramíneas.", condition: "Contiene la Ñ" },
  { letter: "O", answer: "Cosa", description: "Todo lo que tiene entidad, ya sea corporal o espiritual.", condition: "Contiene la O" },
  { letter: "P", answer: "Perro", description: "Mamífero doméstico de la familia de los cánidos.", condition: "Empieza por P" },
  { letter: "Q", answer: "Queso", description: "Producto obtenido por maduración de la cuajada de la leche.", condition: "Empieza por Q" },
  { letter: "R", answer: "Río", description: "Corriente de agua continua y más o menos caudalosa.", condition: "Empieza por R" },
  { letter: "S", answer: "Casa", description: "Edificio para habitar.", condition: "Contiene la S" },
  { letter: "T", answer: "Lata", description: "Envase metálico, generalmente cilíndrico.", condition: "Contiene la T" },
  { letter: "U", answer: "Uva", description: "Baya o grano, fruto de la vid.", condition: "Empieza por U" },
  { letter: "V", answer: "Lava", description: "Materia en fusión que sale de los volcanes.", condition: "Contiene la V" },
  { letter: "W", answer: "Whisky", description: "Bebida alcohólica obtenida por destilación.", condition: "Empieza por W" },
  { letter: "X", answer: "Xenofobia", description: "Fobia a los extranjeros.", condition: "Empieza por X" },
  { letter: "Y", answer: "Yate", description: "Embarcación de gala o de recreo.", condition: "Empieza por Y" },
  { letter: "Z", answer: "Azúcar", description: "Sólido cristalino soluble en agua. Usado como endulzante en alimentos y bebidas.", condition: "Contiene la Z" },
];

export const INITIAL_STATE = (questions: Question[]): Question[] =>
  questions.map(q => ({ ...q, status: STATUS.PENDING }));
